# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 03:08
from __future__ import unicode_literals

import apps.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('crp', 'Cross-platform')], default='', max_length=3)),
                ('applies_to_major_version', models.PositiveSmallIntegerField()),
                ('applies_to_minor_version', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('crp', 'Cross-platform')], default='', max_length=3)),
                ('applies_to_major_version', models.PositiveSmallIntegerField()),
                ('applies_to_minor_version', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to=apps.models.get_icon_path)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('crp', 'Cross-platform')], default='', max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('code_name', models.SlugField(max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('source_code_link', models.URLField(blank=True, default='')),
                ('apple_app_store_link', models.URLField(blank=True, default='')),
                ('bundle_id', models.CharField(blank=True, default='', max_length=100)),
                ('application_id', models.CharField(blank=True, default='', max_length=100)),
                ('google_play_link', models.URLField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('crp', 'Cross-platform')], default='', max_length=3)),
                ('major_version', models.PositiveSmallIntegerField()),
                ('minor_version', models.PositiveSmallIntegerField()),
                ('point_version', models.PositiveSmallIntegerField()),
                ('build_version', models.PositiveSmallIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('what_is_new', models.TextField()),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('app_file', models.FileField(upload_to=apps.models.Release.app_upload_path)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Description')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Icon')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Project')),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('crp', 'Cross-platform')], default='', max_length=3)),
                ('applies_to_major_version', models.PositiveSmallIntegerField()),
                ('applies_to_minor_version', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to=apps.models.get_screenshot_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='release',
            name='screenshots',
            field=models.ManyToManyField(to='apps.Screenshot'),
        ),
        migrations.AddField(
            model_name='icon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Project'),
        ),
        migrations.AddField(
            model_name='description',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Project'),
        ),
    ]
