# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('title', models.TextField()),
                ('short_desc', models.TextField()),
                ('desc', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('platform', models.TextField()),
                ('release_date', models.DateField()),
                ('sunset_date', models.DateField()),
                ('app_icon_path', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
    ]
