# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 23:15
from __future__ import unicode_literals

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_featured_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='androidrelease',
            name='apk_file',
            field=models.FileField(upload_to=apps.models.apk_upload_path),
        ),
        migrations.AlterField(
            model_name='iosrelease',
            name='ipa_file',
            field=models.FileField(upload_to=apps.models.ipa_upload_path),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='icon',
            field=models.ImageField(upload_to=apps.models.overview_icon_upload_path),
        ),
        migrations.AlterField(
            model_name='projectoverviewscreenshot',
            name='screenshot',
            field=models.ImageField(upload_to=apps.models.overview_screenshot_upload_path),
        ),
    ]
