# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20160309_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectoverview',
            name='major_version',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectoverview',
            name='minor_version',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
