# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 13:36
from __future__ import unicode_literals

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20160309_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iosrelease',
            name='manifest_file',
            field=models.FileField(upload_to=apps.models.ipa_upload_path),
        ),
    ]
