# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20160315_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iosrelease',
            name='manifest_file',
        ),
    ]
