# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_iosrelease_manifest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidproject',
            name='google_play_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='iosproject',
            name='apple_app_store_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectoverview',
            name='source_code_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
