# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20160317_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectoverview',
            name='platform',
            field=models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('mlp', 'Multi-Platform')], default='', max_length=3),
        ),
    ]
