# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_projectoverview_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidproject',
            name='application_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iosproject',
            name='bundle_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
