# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20160323_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.CharField(choices=[('', 'No Platform'), ('ios', 'iOS'), ('and', 'Android'), ('win', 'Windows Mobile'), ('mlp', 'Multi-Platform')], default='', max_length=3),
        ),
    ]
